module.exports = {
	content: ['./app/**/*.{ts,tsx,jsx,js}'],
	theme: {
		accentColor: ({ theme }) => ({
			...theme('colors'),
			auto: 'auto',
		}),
		animation: {
			none: 'none',
			spin: 'spin 1s linear infinite',
			ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
			pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
			bounce: 'bounce 1s infinite',
		},
		aria: {
			busy: 'busy="true"',
			checked: 'checked="true"',
			disabled: 'disabled="true"',
			expanded: 'expanded="true"',
			hidden: 'hidden="true"',
			pressed: 'pressed="true"',
			readonly: 'readonly="true"',
			required: 'required="true"',
			selected: 'selected="true"',
		},
		screens: {
			xs: '0px',
			sm: '640px',
			md: '768px',
			lg: '1024px',
			xl: '1280px',
			xxl: '1536px',
		},
		colors: ({ colors }) => ({
			inherit: colors.inherit,
			current: colors.current,
			transparent: colors.transparent,
			black: colors.black,
			white: colors.white,
			slate: colors.slate,
			gray: colors.gray,
			zinc: colors.zinc,
			neutral: colors.neutral,
			stone: colors.stone,
			red: colors.red,
			orange: colors.orange,
			amber: colors.amber,
			yellow: colors.yellow,
			lime: colors.lime,
			green: colors.green,
			emerald: colors.emerald,
			teal: colors.teal,
			cyan: colors.cyan,
			sky: colors.sky,
			blue: colors.blue,
			indigo: colors.indigo,
			violet: colors.violet,
			purple: colors.purple,
			fuchsia: colors.fuchsia,
			pink: colors.pink,
			rose: colors.rose,
		}),
		fontFamily: {
			display: ['Red\\ Hat\\ Display', 'sans-serif'],
			serif: ['Merriweather', 'ui-serif', 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
			'sans-serif': [
				'Inter',
				'ui-sans-serif',
				'system-ui',
				'sans-serif',
				'"Apple Color Emoji"',
				'"Segoe UI Emoji"',
				'"Segoe UI Symbol"',
				'"Noto Color Emoji"',
			],
		},
		extend: {
			gridTemplateRows: {
				layout: '24rem auto',
			},
		},
	},
	plugins: [require('@tailwindcss/typography')],
};
